### ISSUE TITLE
怎么运行

### ISSUE THREAD

**Issue by numen06** [smirkcat/EasyPR-native#1]
这个怎么运行？能不能给个流程说明啊？

**Comment by smirkcat** [comment]
这个项目前还不能运行(我测试了源代码，可能需要修改少量源代码，不然无法加载指定路径的模型文件)，web功能还没有加进去，**图示是去年在公司做的**，代码不能公开，而且那时候用的是opencv2.4.11，现在是opencv3.1.0，所以我需要重构一下，你可以后续关注一下，在oschina中也有地址是`http://git.oschina.net/smirkcat/EasyPR-native`   _**最近有事，暂时搁置了下**_

**Comment by smirkcat** [comment]
**目前更新了c++代码和java接口，已经测试可以调用**
