### ISSUE TITLE
nodejs问题

### ISSUE THREAD

**Issue by tshanchuan** [smirkcat/EasyPR-native#2]
app.js中
const easypr = require('./build/Release/easyprnode');
这个目录在哪里？

**Comment by smirkcat** [comment]
1. 这个我本机环境生成的动态库 我没有上传  这个easyprnode是easyprnode.node文件 也就是 动态库 windows正常成叫easyprnode.dll ；
2. 使用node-gyp 参见网址 [node-gyp](https://github.com/nodejs/node-gyp)  执行 `node-gyp configure` 如果没有错 然后执行`node-gyp build`就会当前目录下有build/Release/easyprnode.node这个文件；
3. 目前nodejs,linux下没测试。

**Comment by tshanchuan** [comment]
在mac 下执行的日志，麻烦大哥帮忙看看什么问题

node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.10.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Library/WebServer/project/EasyPR/easyprnodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/iosdev/.node-gyp/6.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/iosdev/.node-gyp/6.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Library/WebServer/project/EasyPR/easyprnodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
2017-05-25 16:52:05.305 xcodebuild[7134:118375] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp info ok 

----------------------------------------------------------------------------
node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.10.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/easyprnode/src/js.o
In file included from ../src/js.cpp:2:
In file included from ../src/../include/jsobject.h:6:
In file included from ../../NativeEasyPR/include/process.h:2:
In file included from ../../EasyPR/include/easypr/core/plate_recognize.h:15:
In file included from ../../EasyPR/include/easypr/core/plate_detect.h:5:
../../EasyPR/include/easypr/core/plate_judge.h:31:11: error: use of undeclared identifier 'ml'
  cv::Ptr<ml::SVM> svm_;
          ^
In file included from ../src/js.cpp:2:
In file included from ../src/../include/jsobject.h:6:
In file included from ../../NativeEasyPR/include/process.h:2:
In file included from ../../EasyPR/include/easypr/core/plate_recognize.h:16:
In file included from ../../EasyPR/include/easypr/core/chars_recognise.h:16:
../../EasyPR/include/easypr/core/chars_identify.h:45:15: error: no member named 'ml' in namespace 'cv'
  cv::Ptr<cv::ml::ANN_MLP> ann_;
          ~~~~^
../../EasyPR/include/easypr/core/chars_identify.h:48:15: error: no member named 'ml' in namespace 'cv'
  cv::Ptr<cv::ml::ANN_MLP> annChinese_;
          ~~~~^
../../EasyPR/include/easypr/core/chars_identify.h:51:15: error: no member named 'ml' in namespace 'cv'
  cv::Ptr<cv::ml::ANN_MLP> annGray_;
          ~~~~^
../../EasyPR/include/easypr/core/chars_identify.h:54:8: error: no type named 'shared_ptr' in namespace 'std'
  std::shared_ptr<Kv> kv_;
  ~~~~~^
../../EasyPR/include/easypr/core/chars_identify.h:54:18: error: expected member name or ';' after declaration specifiers
  std::shared_ptr<Kv> kv_;
  ~~~~~~~~~~~~~~~^
In file included from ../src/js.cpp:2:
In file included from ../src/../include/jsobject.h:6:
In file included from ../../NativeEasyPR/include/process.h:2:
In file included from ../../EasyPR/include/easypr/core/plate_recognize.h:16:
In file included from ../../EasyPR/include/easypr/core/chars_recognise.h:17:
../../EasyPR/include/easypr/core/core_func.h:63:18: error: use of undeclared identifier 'LINE_8'
  int lineType = LINE_8, int shift = 0);
                 ^
In file included from ../src/js.cpp:2:
In file included from ../src/../include/jsobject.h:6:
In file included from ../../NativeEasyPR/include/process.h:2:
In file included from ../../EasyPR/include/easypr/core/plate_recognize.h:16:
In file included from ../../EasyPR/include/easypr/core/chars_recognise.h:18:
../../EasyPR/include/easypr/util/util.h:75:42: error: no type named 'initializer_list' in namespace 'std'
  static void print_str_lines(const std::initializer_list<const char*> &lines) {
                                    ~~~~~^
../../EasyPR/include/easypr/util/util.h:75:58: error: expected ')'
  static void print_str_lines(const std::initializer_list<const char*> &lines) {
                                                         ^
../../EasyPR/include/easypr/util/util.h:75:30: note: to match this '('
  static void print_str_lines(const std::initializer_list<const char*> &lines) {
                             ^
../../EasyPR/include/easypr/util/util.h:76:22: error: use of undeclared identifier 'lines'; did you mean 'line'?
    for (auto line : lines) {
                     ^~~~~
                     line
../../EasyPR/include/easypr/util/util.h:76:15: note: 'line' declared here
    for (auto line : lines) {
              ^
../../EasyPR/include/easypr/util/util.h:76:20: error: invalid range expression of type 'auto'; no viable 'begin' function available
    for (auto line : lines) {
                   ^ ~~~~~
../../EasyPR/include/easypr/util/util.h:85:19: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char>')
    std::ifstream fs(file);
                  ^  ~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1/fstream:465:7: note: candidate constructor not viable: no known conversion from 'const std::string' (aka 'const basic_string<char>') to 'const char *' for 1st argument
      basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1/bits/fstream.tcc:894:25: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const std::string' (aka 'const basic_string<char>') to 'const std::basic_ifstream<char>' for 1st argument
  extern template class basic_ifstream<char>;
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1/fstream:451:7: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
      basic_ifstream() : __istream_type(), _M_filebuf()
      ^
In file included from ../src/js.cpp:2:
In file included from ../src/../include/jsobject.h:6:
In file included from ../../NativeEasyPR/include/process.h:2:
In file included from ../../EasyPR/include/easypr/core/plate_recognize.h:15:
In file included from ../../EasyPR/include/easypr/core/plate_detect.h:4:
In file included from ../../EasyPR/include/easypr/core/plate_locate.h:17:
../../EasyPR/include/easypr/core/plate.hpp:180:9: warning: private field 'm_charCount' is not used [-Wunused-private-field]
    int m_charCount;
        ^
1 warning and 12 errors generated.
make: *** [Release/obj.target/easyprnode/src/js.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Library/WebServer/project/EasyPR/easyprnodejs
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

**Comment by smirkcat** [comment]
我没有写mac系统的依赖 肯定会失败 这个只在windows下编译成功 在binding.gyp文件中需要添加mac的依赖才能成功，我目前没有mac环境，以前的环境坏掉了 对binding.gyp 写法我还不是很会 所以只编译了windows release64位

**Comment by smirkcat** [comment]
最近更新了linux和mac的写法，linux已经测试完成， mac没有环境无法测试了 正常来说 你编译好NativeEasyPR 就可以，这个node addon没问题，注意 这个需要依赖NativeEasyPR编译的库。
