### ISSUE TITLE
你好  我想问问JavaWeb版的问题

### ISSUE THREAD

**Issue by xiaoheiAh** [smirkcat/EasyPR-native#3]
我下了最新的EasyPR源码编译成功运行了，然后想用你的javaweb研究研究调用，但是替换那三个文件有点摸不着门，编译会报错，我没有学过C++所以并不是很懂这个。
![image](https://cloud.githubusercontent.com/assets/27981726/26719697/1b130da4-47b8-11e7-82b0-109debd26598.png)
有这么些错，求指导下，没有jni.h kv是私有的不能调用 是不是我替换有问题呢？

**Comment by smirkcat** [comment]
首先你配置了JAVA_HOME环境变量么，没有配置就找不到jni.h，这个private肯定是你没替换成功吧，正常是public能调用 
![default](https://cloud.githubusercontent.com/assets/13444394/26720845/3d0c8ce2-47bc-11e7-8a00-632ec8d3619c.png)
