### ISSUE TITLE
make提示找不到jni.h

### ISSUE THREAD

**Issue by developer-young** [smirkcat/EasyPR-native#4]
我打算将EsayPR移植Linux系统上，都按照你的要求做了，到make这一步提示我找不到jni.h这个错误

**Comment by smirkcat** [comment]
![default](https://user-images.githubusercontent.com/13444394/27727867-d79de0f6-5db2-11e7-978e-5c135403c175.png)
安装java环境没 然后设置$JAVA_HOME 环境变量

**Comment by developer-young** [comment]
原来是这个问题，谢谢了
