### ISSUE TITLE
OpenCV Error: Parsing error (Missing or invalid SVM type) in read_params in MAC JAVA

### ISSUE THREAD

**Issue by gqsteven** [smirkcat/EasyPR-native#6]
想求教下 因为完全不懂这个错，想请你帮忙看看。
我用最新的代码打的包 只改了kv_私有化的问题。当运行EasyPRTest出现以下的错，是EasyPR初始化时 抛出。
/Users/xxxxxxx/Downloads/EasyPR-native-master/easyprjava/target/test-classes/
加载动态库easyprjni完成
OpenCV Error: Parsing error (Missing or invalid SVM type) in read_params, file /tmp/opencv3-20161231-93843-1a11dpc/opencv-3.2.0/modules/ml/src/svm.cpp, line 2123
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20161231-93843-1a11dpc/opencv-3.2.0/modules/ml/src/svm.cpp:2123: error: (-212) Missing or invalid SVM type in function read_params

**Comment by smirkcat** [comment]
最新版是用opencv3.2.0 估计模型文件什么的应该都变了吧 我用的是opencv3.1.0版本 是以前1.5版本 最新版的应该可能有问题 你把那几个模型文件替换一下？

**Comment by gqsteven** [comment]
已经试过了 一样的 我把模型文件删空还是一样的exception。。。应该与模型文件没关系

**Comment by smirkcat** [comment]
这个你换成[aec8ddab4308f7e24487e97bcb32a6f5f6f17c4e](https://github.com/liuruoze/EasyPR/tree/aec8ddab4308f7e24487e97bcb32a6f5f6f17c4e) 这个分支吧 我是去年这个时候弄的 现在没时间弄这个了 1.6版本我没弄 你先换成先前的版本 然后跑通了 然后你试着换下

还有我把这些地方是注释了的
![default](https://user-images.githubusercontent.com/13444394/28346552-4ab9430e-6c64-11e7-9436-24cf58b33516.png)
 你看着改下
