### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by inkpei** [smirkcat/EasyPR-native#8]
windows 和 Linux 下运行python版本均报此错误 但用ctypes导入其他DLL文件不会报错

**Comment by smirkcat** [comment]
@inkpei 其他版本运行成功过么 opencv的运行依赖库能找到么

**Comment by fengzhenzhu** [comment]
我也遇到了这个错误，请问有没有人知道怎么解决呢？
